### ISSUE TITLE
User profile bug

### ISSUE THREAD

**Issue by cvetko12** [aimeos/aimeos-typo3#243]
While using user profile (fe_users), if you save payment address, it will create empty delivery address.
My best guess is that both save buttons have the same name tag (ai[address][save]), or it could be ignoring the ID that is in form data:

ai[address][payment][customer.firstname]: Name
ai[address][payment][customer.lastname]: Surename
ai[address][payment][customer.company]: 
ai[address][payment][customer.address1]: Addr
ai[address][payment][customer.city]: City
ai[address][payment][customer.postal]: 123123
ai[address][payment][customer.countryid]: EN
ai[address][payment][customer.languageid]: en
ai[address][payment][customer.email]: email@email.com
ai[address][payment][customer.telephone]: 012301230123
ai[address][save]: 1
ai[address][delivery][1][customer.address.firstname]: 
ai[address][delivery][1][customer.address.lastname]: 
ai[address][delivery][1][customer.address.company]: 
ai[address][delivery][1][customer.address.address1]: 
ai[address][delivery][1][customer.address.city]: 
ai[address][delivery][1][customer.address.postal]: 
ai[address][delivery][1][customer.address.countryid]: 
ai[address][delivery][1][customer.address.languageid]: en
ai[address][delivery][1][customer.address.telephone]:

**Comment by cvetko12** [comment]
For anyone else having the same problem, I fixed it by adding this code in typo3conf/ext/aimeos/Resources/Libraries/aimeos/ai-client-html/src/Client/Html/Account/Profile/Standard.php init() function
``php

	$check_keys = [
		'customer.address.firstname',
		'customer.address.lastname',
		'customer.address.company',
		'customer.address.address1',
		'customer.address.city',
		'customer.address.postal',
		'customer.address.countryid',
		'customer.address.telephone',
	];

	foreach($map as $key => $cleanup) {
		$remove = true;
		foreach($check_keys as $check_key) {
			if(!empty($cleanup[$check_key])) {
				$remove = false;
				break;
			}
		}

		if($remove) {
			unset($map[$key]);
		}
	}
``

I'm not sure if this problem is only with my setup or if its actually a bug in account/profile module, but it seems like its always posting address-delivery-new form and inserting it even if its empty.

**Comment by aimeos** [comment]
Thank you for your bug report!
The problem is that the fields are not disabled and sent by the browser and we will check why that happens.

**Comment by aimeos** [comment]
The problem is fixed now in aimeos/ai-client-html dev-master and 2024.10.x-dev and will be part of the next release.

**Comment by aimeos** [comment]
Thanks a lot! The hidden "customer.address.id" is now disabled by default. Can you check, please?

**Comment by cvetko12** [comment]
Still not quit right, in this case it removes delivery address. I think we could change it in a way that it sends ID with it, and just ignores validation in case the only data is ID, or don't pass that ID by default and only call addresses that are in "address/delete" parameter? Because currently its removing all the leftover that doesn't get created or updated.

**Comment by cvetko12** [comment]
How about we just change the loop like this:

	public function init()
	{
		$view = $this->view();
		$data = $view->param( 'address/payment', [] );

		if( !$view->param( 'address/save' ) && !$view->param( 'address/delete' ) ) {
			return;
		}

		if( !empty( $data ) && ( $view->addressPaymentError = $this->checkFields( $data, 'payment' ) ) !== [] ) {
			throw new \Aimeos\Client\Html\Exception( sprintf( 'At least one payment address part is missing or invalid' ) );
		}

		$cntl = \Aimeos\Controller\Frontend::create( $this->context(), 'customer' );
		$addrItems = $cntl->uses( ['customer/address'] )->get()->getAddressItems();
		$cntl->add( $view->param( 'address/payment', [] ) );

		$map = $view->param( 'address/delivery', [] );

		foreach( $map as $pos => $data )
		{
			if( ( $view->addressDeliveryError = $this->checkFields( $data, 'delivery' ) ) !== [] ) {
				throw new \Aimeos\Client\Html\Exception( sprintf( 'At least one delivery address part is missing or invalid' ) );
			}

			$addrItem = $addrItems->get( $pos ) ?: $cntl->createAddressItem();
			$cntl->addAddressItem( $addrItem->fromArray( $data ), $pos );
			$addrItems->remove( $pos );
		}

		foreach( $addrItems as $addrItem ) {
			// Check if address matches the delete parameter
			if($view->param( 'address/delete' ) == $addrItem->getId()) {
				$cntl->deleteAddressItem( $addrItem );
				break;
			}
		}

		$cntl->store();
	}

**Comment by cvetko12** [comment]
How about we change it like that and it should work:

	public function init()
	{
		$view = $this->view();
		$data = $view->param( 'address/payment', [] );

		if( !$view->param( 'address/save' ) && !$view->param( 'address/delete' ) ) {
			return;
		}


		if( !empty( $data ) && ( $view->addressPaymentError = $this->checkFields( $data, 'payment' ) ) !== [] ) {
			throw new \Aimeos\Client\Html\Exception( sprintf( 'At least one payment address part is missing or invalid' ) );
		}

		$cntl = \Aimeos\Controller\Frontend::create( $this->context(), 'customer' );
		$addrItems = $cntl->uses( ['customer/address'] )->get()->getAddressItems();
		$cntl->add( $view->param( 'address/payment', [] ) );

		$map = $view->param( 'address/delivery', [] );

		if( $pos = $view->param( 'address/delete' ) ) {
			unset( $map[$pos] );
		}

		foreach( $map as $pos => $data )
		{
			if( ( $view->addressDeliveryError = $this->checkFields( $data, 'delivery' ) ) !== [] ) {
				throw new \Aimeos\Client\Html\Exception( sprintf( 'At least one delivery address part is missing or invalid' ) );
			}

			$addrItem = $addrItems->get( $pos ) ?: $cntl->createAddressItem();
			$cntl->addAddressItem( $addrItem->fromArray( $data ), $pos );
			$addrItems->remove( $pos );
		}

		foreach( $addrItems as $addrItem ) {
			if($view->param( 'address/delete' ) == $addrItem->getId()) {
				$cntl->deleteAddressItem( $addrItem );
			}
		}

		$cntl->store();
	}

In this case it will bypass validation and check if it should be deleted, if none of those cases happen, it will just pass it.

**Comment by aimeos** [comment]
Good idea! We've simplified the code a bit and now it should work. Can you confirm?

**Comment by cvetko12** [comment]
It now works as expected

**Comment by cvetko12** [comment]
Since I already opened this ticket I have a question, and I'll post it here if that's alright.

I'm trying to extend customer to have additional fields (emso, personalvat, and birthplace) inside "address/payment" (that should be stored in fe_users table), so I created a new TYPO3 extension that extends Aimeos, and tried extending MShop/Customer/Manager/Standard.php to overwrite create() and from there I would return different Customer Item that includes those additional fields.

I tried adding manager to config/mshop.php:
```php
<?php

return [
    'customer' => [
        'manager' => [
           'name' => 'AdditionalFields'
        ],
    ],
    // Im also overwriting order manager to include those fields when someone order but in that case it works
    'order' => [
        'manager' => [
            'address' => [
                'name' => 'AdditionalFields',
            ],
        ],
    ],
];
```


 MShop/Customer/Item/AdditionalFields.php:
```php
<?
namespace Aimeos\MShop\Customer\Item;

class AdditionalFields extends \Aimeos\MShop\Customer\Item\Standard
{
    public function getPersonalVat(): string
    {
        return $this->get('customer.personalvat', '');
    }

    public function setPersonalVat(?string $personalvat): \Aimeos\MShop\Customer\Item\Iface
    {
        return $this->set('customer.personalvat', $personalvat);
    }

    public function getBirthplace(): string
    {
        return $this->get('customer.birthplace', '');
    }

    public function setBirthplace(?string $birthplace): \Aimeos\MShop\Customer\Item\Iface
    {
        return $this->set('customer.birthplace', $birthplace);
    }

    public function fromArray(array &$list, bool $private = false): \Aimeos\MShop\Common\Item\Iface
    {
        $item = parent::fromArray($list, $private);

        foreach ($list as $key => $value) {
            switch ($key) {
                case 'customer.emso':
                    $item->setEmso($value);
                    break;
                case 'customer.personalvat':
                    $item->setPersonalVat($value);
                    break;
                case 'customer.birthplace':
                    $item->setBirthplace($value);
                    break;
                default:
                    continue 2;
            }
            unset($list[$key]);
        }

        return $item;
    }

    public function toArray(bool $private = false): array
    {
        $list = parent::toArray($private);

        if ($private) {
            $list['customer.emso'] = $this->getEmso();
            $list['customer.personalvat'] = $this->getPersonalVat();
            $list['customer.birthplace'] = $this->getBirthplace();
        }

        return $list;
    }
}
```

But the problem is that my customized manager never gets called, it always goes to the Standard managers create() function.
What am I missing here? Do I even understand the concept correctly?

**Comment by aimeos** [comment]
Please create a new topic in the Aimeos forum (https://aimeos.org/help) because the Github issues are only for bug reports.

**Comment by cvetko12** [comment]
@aimeos Thank you for your reply. I tried making account on the forum, but it seems like forum isn't sending out emails, and I can't confirm my account.. I also tried logging in with Google Account but I still didn't receive any confirmation email.

**Comment by cvetko12** [comment]
Yes, of course, I checked spam folder, I tried signing in with Google Account (OAuth), Github (OAuth). I always get this message "The account has been created. However, the forum settings require account activation. An activation key has been sent to your email address.", also tried re sending activation email a bunch of time, and didn't receive it. I'll try with protonmail later and I'll update you if that works...
