### ISSUE TITLE
Image disappears after replace it in copied product

### ISSUE THREAD

**Issue by noll1** [aimeos/aimeos-typo3#85]
After I copied a product and replace the image with a new one, the old product picture is not available anymore.
Steps to reproduce:
1. Create new product and save it:
![new_product](https://user-images.githubusercontent.com/42864489/49287072-64527080-f49c-11e8-8b9b-ffbf5a8ea958.png)
In the list you see the product with his image.
![new_product_in_list](https://user-images.githubusercontent.com/42864489/49287106-7fbd7b80-f49c-11e8-8b95-0871894c7e7e.png)
2. Copy the created product in the product overview:
![copy_product](https://user-images.githubusercontent.com/42864489/49287126-949a0f00-f49c-11e8-8eae-e0d312ca8055.png)
3. I changed the SKU, Label, replaced the image and saved it:
![copied_product](https://user-images.githubusercontent.com/42864489/49287141-ada2c000-f49c-11e8-803d-125503d9e9c7.png)
4. Now you see in the list, that the old product image is missing:
![missing_image](https://user-images.githubusercontent.com/42864489/49287183-cc08bb80-f49c-11e8-9224-194e5a2f4e6a.png)

**Comment by aimeos** [comment]
The problem has been fixed in the 2018.10 branch. If you use composer, you can add this to the `require` section of your `composer.json`:
```
"aimeos/ai-admin-jqadm": "2018.10.x-dev"
```
After executing `composer update`, the new package is available and you can test it yourself. We will tag a new version soon.

**Comment by noll1** [comment]
I don't use composer so I replaced the "ai-admin-jqadm" directory with the current one from master.
For me the problem is still there when I follow the process described above.

**Comment by aimeos** [comment]
Finally fixed in https://github.com/aimeos/ai-admin-jqadm/commit/d9aca65e66ae16defc6288cf19cc558871dcb076

**Comment by noll1** [comment]
Problem solved, thank you!
